 #Name of the workflow as it will appear in the GitHub Actions tabAdd commentMore actions
name: Deploy AWS Infrastructure with Terraform

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan & Apply           # Name of the job
    runs-on: ubuntu-latest                 # Use the latest Ubuntu runner

    # Environment variables for AWS authentication (from GitHub Secrets)
    env:
      AWS_ACCESS_KEY_ID: ${{AKIATRDMOGW7ZUUQ734B}}
      AWS_SECRET_ACCESS_KEY: ${{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}}

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repo
      uses: actions/checkout@v3

    # Step 2: Install the specified version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    # Step 3: Initialize the Terraform working directory
    - name: Terraform Init
      run: terraform init

    # Step 4: Validate Terraform code to catch syntax or config errors
    - name: Terraform Validate
      run: terraf
